2021-02-23 18:16:18,474 p=4078 u=root n=ansible | Using /etc/ansible/ansible.cfg as config file
2021-02-23 18:16:18,474 p=4078 u=root n=ansible | ERROR! the playbook: ec2_provisioning.yml could not be found
2021-02-24 14:13:59,461 p=10919 u=ubuntu n=ansible | ERROR! the playbook: instance_type=ami-0915bcb5fa77e4892 could not be found
2021-02-24 14:15:24,623 p=10933 u=ubuntu n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2021-02-24 14:15:24,949 p=10933 u=ubuntu n=ansible | PLAY [localhost] *******************************************************************************************************************************************************
2021-02-24 14:15:24,963 p=10933 u=ubuntu n=ansible | TASK [include_vars] ****************************************************************************************************************************************************
2021-02-24 14:15:24,976 p=10933 u=ubuntu n=ansible | fatal: [localhost]: FAILED! => {"ansible_facts": {}, "ansible_included_var_files": [], "changed": false, "message": "Could not find or access '/ansible_repo/prov_aws_ec2_ansible_2/variables/variables.yml' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
2021-02-24 14:15:24,977 p=10933 u=ubuntu n=ansible | PLAY RECAP *************************************************************************************************************************************************************
2021-02-24 14:15:24,978 p=10933 u=ubuntu n=ansible | localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2021-02-24 14:16:54,042 p=10944 u=ubuntu n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2021-02-24 14:16:54,350 p=10944 u=ubuntu n=ansible | PLAY [localhost] *******************************************************************************************************************************************************
2021-02-24 14:16:54,364 p=10944 u=ubuntu n=ansible | TASK [include_vars] ****************************************************************************************************************************************************
2021-02-24 14:16:54,375 p=10948 u=ubuntu n=ansible | [WARNING]: While constructing a mapping from /ansible_repo/prov_aws_ec2_ansible_2/variables/variable.yml, line 1, column 1, found a duplicate dict key (ec2_tag_Role).
Using last defined value only.

2021-02-24 14:16:54,378 p=10944 u=ubuntu n=ansible | ok: [localhost]
2021-02-24 14:16:54,411 p=10944 u=ubuntu n=ansible | TASK [Provision one instances] *****************************************************************************************************************************************
2021-02-24 14:16:54,426 p=10944 u=ubuntu n=ansible | fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ec2_image' is undefined\n\nThe error appears to be in '/ansible_repo/prov_aws_ec2_ansible_2/playbooks/ec2_provisioning_1.yml': line 10, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Provision {{ ec2_count }} instances\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
2021-02-24 14:16:54,428 p=10944 u=ubuntu n=ansible | PLAY RECAP *************************************************************************************************************************************************************
2021-02-24 14:16:54,429 p=10944 u=ubuntu n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2021-02-24 14:18:02,719 p=10959 u=ubuntu n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2021-02-24 14:18:03,033 p=10959 u=ubuntu n=ansible | PLAY [localhost] *******************************************************************************************************************************************************
2021-02-24 14:18:03,046 p=10959 u=ubuntu n=ansible | TASK [include_vars] ****************************************************************************************************************************************************
2021-02-24 14:18:03,058 p=10963 u=ubuntu n=ansible | [WARNING]: While constructing a mapping from /ansible_repo/prov_aws_ec2_ansible_2/variables/variable.yml, line 1, column 1, found a duplicate dict key (ec2_tag_Role).
Using last defined value only.

2021-02-24 14:18:03,061 p=10959 u=ubuntu n=ansible | ok: [localhost]
2021-02-24 14:18:03,094 p=10959 u=ubuntu n=ansible | TASK [Provision one instances] *****************************************************************************************************************************************
2021-02-24 14:18:03,894 p=10959 u=ubuntu n=ansible | fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "argument exact_count is of type <class 'str'> and we were unable to convert to int: <class 'str'> cannot be converted to an int"}
2021-02-24 14:18:03,896 p=10959 u=ubuntu n=ansible | PLAY RECAP *************************************************************************************************************************************************************
2021-02-24 14:18:03,897 p=10959 u=ubuntu n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2021-02-24 14:18:56,462 p=11003 u=ubuntu n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2021-02-24 14:18:56,787 p=11003 u=ubuntu n=ansible | PLAY [localhost] *******************************************************************************************************************************************************
2021-02-24 14:18:56,800 p=11003 u=ubuntu n=ansible | TASK [include_vars] ****************************************************************************************************************************************************
2021-02-24 14:18:56,812 p=11007 u=ubuntu n=ansible | [WARNING]: While constructing a mapping from /ansible_repo/prov_aws_ec2_ansible_2/variables/variable.yml, line 1, column 1, found a duplicate dict key (ec2_tag_Role).
Using last defined value only.

2021-02-24 14:18:56,814 p=11003 u=ubuntu n=ansible | ok: [localhost]
2021-02-24 14:18:56,848 p=11003 u=ubuntu n=ansible | TASK [Provision 1 instances] *******************************************************************************************************************************************
2021-02-24 14:18:57,461 p=11003 u=ubuntu n=ansible | fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials"}
2021-02-24 14:18:57,463 p=11003 u=ubuntu n=ansible | PLAY RECAP *************************************************************************************************************************************************************
2021-02-24 14:18:57,464 p=11003 u=ubuntu n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2021-02-24 14:19:47,357 p=11036 u=ubuntu n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2021-02-24 14:19:47,674 p=11036 u=ubuntu n=ansible | PLAY [localhost] *******************************************************************************************************************************************************
2021-02-24 14:19:47,687 p=11036 u=ubuntu n=ansible | TASK [include_vars] ****************************************************************************************************************************************************
2021-02-24 14:19:47,702 p=11036 u=ubuntu n=ansible | ok: [localhost]
2021-02-24 14:19:47,735 p=11036 u=ubuntu n=ansible | TASK [Provision 1 instances] *******************************************************************************************************************************************
2021-02-24 14:19:48,357 p=11036 u=ubuntu n=ansible | fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials"}
2021-02-24 14:19:48,359 p=11036 u=ubuntu n=ansible | PLAY RECAP *************************************************************************************************************************************************************
2021-02-24 14:19:48,359 p=11036 u=ubuntu n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2021-02-24 14:21:06,606 p=11070 u=ubuntu n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2021-02-24 14:21:06,917 p=11070 u=ubuntu n=ansible | PLAY [localhost] *******************************************************************************************************************************************************
2021-02-24 14:21:06,930 p=11070 u=ubuntu n=ansible | TASK [include_vars] ****************************************************************************************************************************************************
2021-02-24 14:21:06,945 p=11070 u=ubuntu n=ansible | ok: [localhost]
2021-02-24 14:21:06,978 p=11070 u=ubuntu n=ansible | TASK [Provision 1 instances] *******************************************************************************************************************************************
2021-02-24 14:21:07,596 p=11070 u=ubuntu n=ansible | fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials"}
2021-02-24 14:21:07,599 p=11070 u=ubuntu n=ansible | PLAY RECAP *************************************************************************************************************************************************************
2021-02-24 14:21:07,599 p=11070 u=ubuntu n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2021-02-24 14:25:47,126 p=11132 u=ubuntu n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2021-02-24 14:25:47,437 p=11132 u=ubuntu n=ansible | PLAY [localhost] *******************************************************************************************************************************************************
2021-02-24 14:25:47,450 p=11132 u=ubuntu n=ansible | TASK [include_vars] ****************************************************************************************************************************************************
2021-02-24 14:25:47,464 p=11132 u=ubuntu n=ansible | ok: [localhost]
2021-02-24 14:25:47,497 p=11132 u=ubuntu n=ansible | TASK [Provision 1 instances] *******************************************************************************************************************************************
2021-02-24 14:25:48,119 p=11132 u=ubuntu n=ansible | fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials"}
2021-02-24 14:25:48,122 p=11132 u=ubuntu n=ansible | PLAY RECAP *************************************************************************************************************************************************************
2021-02-24 14:25:48,122 p=11132 u=ubuntu n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2021-02-24 14:30:06,000 p=11169 u=ubuntu n=ansible | Using /etc/ansible/ansible.cfg as config file
2021-02-24 14:30:06,000 p=11169 u=ubuntu n=ansible | ERROR! the playbook: ec2_host=vishal could not be found
2021-02-24 14:31:05,333 p=11181 u=ubuntu n=ansible | Using /etc/ansible/ansible.cfg as config file
2021-02-24 14:31:05,334 p=11181 u=ubuntu n=ansible | ERROR! the playbook: ec2_host=vishal could not be found
2021-02-24 14:32:21,464 p=11188 u=ubuntu n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2021-02-24 14:32:21,744 p=11188 u=ubuntu n=ansible | PLAY [localhost] *******************************************************************************************************************************************************
2021-02-24 14:32:21,757 p=11188 u=ubuntu n=ansible | TASK [Gathering Facts] *************************************************************************************************************************************************
2021-02-24 14:32:22,705 p=11188 u=ubuntu n=ansible | ok: [localhost]
2021-02-24 14:32:22,714 p=11188 u=ubuntu n=ansible | TASK [Create ec2 instance from launch template] ************************************************************************************************************************
2021-02-24 14:32:22,758 p=11188 u=ubuntu n=ansible | fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ec2_host' is undefined\n\nThe error appears to be in '/ansible_repo/prov_aws_ec2_ansible_2/playbooks/ec2_provisioning.yml': line 11, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Create ec2 instance from launch template\n      ^ here\n"}
2021-02-24 14:32:22,761 p=11188 u=ubuntu n=ansible | PLAY RECAP *************************************************************************************************************************************************************
2021-02-24 14:32:22,761 p=11188 u=ubuntu n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2021-02-24 14:32:51,612 p=11265 u=ubuntu n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2021-02-24 14:32:51,890 p=11265 u=ubuntu n=ansible | PLAY [localhost] *******************************************************************************************************************************************************
2021-02-24 14:32:51,903 p=11265 u=ubuntu n=ansible | TASK [Gathering Facts] *************************************************************************************************************************************************
2021-02-24 14:32:52,825 p=11265 u=ubuntu n=ansible | ok: [localhost]
2021-02-24 14:32:52,833 p=11265 u=ubuntu n=ansible | TASK [Create ec2 instance from launch template] ************************************************************************************************************************
2021-02-24 14:32:53,979 p=11265 u=ubuntu n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.NoCredentialsError: Unable to locate credentials
2021-02-24 14:32:53,979 p=11265 u=ubuntu n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1614177172.8769875-150782821203887/AnsiballZ_ec2_instance.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1614177172.8769875-150782821203887/AnsiballZ_ec2_instance.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1614177172.8769875-150782821203887/AnsiballZ_ec2_instance.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.amazon.ec2_instance', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ec2_instance_payload_4mv7d33k/ansible_ec2_instance_payload.zip/ansible/modules/cloud/amazon/ec2_instance.py\", line 1710, in <module>\n  File \"/tmp/ansible_ec2_instance_payload_4mv7d33k/ansible_ec2_instance_payload.zip/ansible/modules/cloud/amazon/ec2_instance.py\", line 1681, in main\n  File \"/tmp/ansible_ec2_instance_payload_4mv7d33k/ansible_ec2_instance_payload.zip/ansible/modules/cloud/amazon/ec2_instance.py\", line 1300, in find_instances\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/botocore/paginate.py\", line 322, in search\n    for page in self:\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/botocore/paginate.py\", line 255, in __iter__\n    response = self._make_request(current_kwargs)\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/botocore/paginate.py\", line 332, in _make_request\n    return self._method(**current_kwargs)\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/botocore/client.py\", line 662, in _make_api_call\n    http, parsed_response = self._make_request(\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/botocore/client.py\", line 682, in _make_request\n    return self._endpoint.make_request(operation_model, request_dict)\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/botocore/endpoint.py\", line 102, in make_request\n    return self._send_request(request_dict, operation_model)\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/botocore/endpoint.py\", line 132, in _send_request\n    request = self.create_request(request_dict, operation_model)\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/botocore/endpoint.py\", line 115, in create_request\n    self._event_emitter.emit(event_name, request=request,\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py\", line 356, in emit\n    return self._emitter.emit(aliased_event_name, **kwargs)\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py\", line 228, in emit\n    return self._emit(event_name, kwargs)\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/botocore/hooks.py\", line 211, in _emit\n    response = handler(**kwargs)\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/botocore/signers.py\", line 90, in handler\n    return self.sign(operation_name, request)\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/botocore/signers.py\", line 162, in sign\n    auth.add_auth(request)\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/botocore/auth.py\", line 357, in add_auth\n    raise NoCredentialsError\nbotocore.exceptions.NoCredentialsError: Unable to locate credentials\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2021-02-24 14:32:53,981 p=11265 u=ubuntu n=ansible | PLAY RECAP *************************************************************************************************************************************************************
2021-02-24 14:32:53,982 p=11265 u=ubuntu n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
